inherit_from: ${FACTNERF_ROOT}/configs/SYN/sce_b_ini.yaml

verbose: true 
script_name:  opt_syn

render_dw_step: 2
render_points_batch_size: 128
render_ray_batch_size: 64

sce_type: occ_v2

data: 
    output_root: ${FACTNERF_ROOT}/output/SYN/nice

opt_2:   
  opt_mode:  [ 'mapping' ]

  mapping:

      pre_train_wt: null
      pretrain_single_obj: False
      
      run_joint: True
      run_BA: False

      joint: 
          total_iters:       21000
          snapshot_interval:  5000
          vis_interval:       5000
          pose_vis_interval: -1 
          
          use_middle_to_fine_training: True
          middle_iters: 500
          fine_iters:   500

          early_stop_th:    1.0e-5

          eikonal_sample_num: 2048
          collect_sample_mask_mode: v2_seg

          rand_sample_num:     256   # N/# img /# obj = sample per images
          rand_img_per_batch:  4
          
          loss:
              - [ obj_color,           1.0   ]
              - [ obj_depth,           0.5   ] 
              - [ objvec_L1,           100.0   ]

          opt_dmnet_aft:      0

          ini_net_lr:       1.0e-3
          ini_sce_lr:       1.0e-3
          ini_deform_lr:    1.0e-4
          ini_rigidpose_lr: 1.0e-4
          ini_tocde_lr:     1.0e-4

          lr_decay_ratio:   0.5
          min_lr:        1.0e-6

          sce_decay_lr_at:        []
          net_decay_lr_at:        []
          deformnet_decay_lr_at:  []
          rigidpose_decay_lr_at:  []
          tcode_decay_lr_at:      []

          use_deform_win_a:        False
          deform_win_a_delay_step: 2000
          deform_win_a_interval:   2000
          deform_win_a_min: 0.0

          use_deform_win_b:        False
          deform_win_b_interval:   10000
          deform_win_b_delay_step: 20000 
 

shared: 
    debug_time:      False
    ray_sample_num:  128
    max_pre_samples: 1024

    pose_init_mode:   est_pose_v1
    gt_pose_mode:     frame0

    train_sample_alg: v6_balanced_obj_freespace
    ray_sample_mode:  uniform_inv_uniform_x4 
    ray_sample_num:   128

    apply_depth_filtering: False
    check_grad: True

    segment_mode: siammask 
    bbox_mode: anno

    vis_all: False
    vis_obj: True
    
    vis_frames_indices:   [0,19] 
    #output_frame_indices: [0,19]  
    #eval_frame_indices:   [0,19] 

    opt_frames_num: -1
    opt_eval_fidx_step: 10

#==========================================
sce_model: 
  module: src.my_model.niceslam
  class:  NICE_wraper
  args:
    middle_reso: [32,32,32]
    fine_reso:   [64,64,64]
    color_reso:  [64,64,64]

#==========================================
network:
  module: src.my_model.niceslam
  class:  MainMLP
  args:  
    use_stage: True

#==========================================
rigid_posenet: 
  module: src.my_model.motion
  class:  RigidPoses_wTCodes 
  args: 
    t_dim: 32 
    optimize_pose:  False
    use_cano_frame: True
    cano_idx: 0  

nonrigid_posenet: 
  module: src.my_model.motion
  class:  RigidPoses_BijMap_wTCodes
  args:   
    optimize_rigid_pose: True
    bij_use_wn: False
    t_dim: 32
    uv_min_deg: 0
    uv_max_deg: 6
    w_min_deg:  0
    w_max_deg:  6
    use_cano_frame: True
    cano_idx: 0 

