inherit_from: ${FACTNERF_ROOT}/configs/SYN/niceslam/sce_a_nice.yaml


shared: 
    g_obj_uids:     [0]
    g_obj_is_rigid: [1]

    ray_step_size: [0.08]

    train_sample_alg: v3_sample_mask

opt_2:    
  mapping: 
      joint:  
          loss:
              - [ obj_color,       1.0   ]
              - [ obj_depth,       0.5   ] 
              #-[ objvec_L1,     100.0   ]

#==========================================
sce_model: 
  module: src.my_model.niceslam
  class:  NICE_wraper
  args:
    middle_reso: [32,32,32]
    fine_reso:   [80,80,80]
    color_reso:  [80,80,80]