
FROM  nvidia/cudagl:11.3.0-devel-ubuntu20.04
RUN apt-get update 
RUN apt-get install -y --no-install-recommends apt-utils sudo 
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install --no-install-recommends  -y alien

RUN apt-get install -y --no-install-recommends \
    pkg-config \
    build-essential \
    cmake \
    git \
    curl \
    vim \ 
    ca-certificates \
    gcc \
    g++ \
    gdb \ 
    x11-apps \
    wget 

RUN apt-get -y install curl bzip2  

RUN curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh     && bash /tmp/miniconda.sh -bfp /usr/local     && rm -rf /tmp/miniconda.sh     && conda install -y python=3.8    && conda update conda     

#---------------------------
ENV MY_CUDA_PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin 
ENV MY_CONDA_PATH=/usr/local/bin

ENV TORCH_CUDA_ARCH_LIST="8.6"

RUN conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=11.3 cudnn=8 -c pytorch -c conda-forge
RUN conda install -c conda-forge pybind11 matplotlib pyvisa pybind11 colorama ipyvtklink
RUN conda install pytorch-scatter -c pyg  

RUN apt-get update && apt-get install -y --no-install-recommends \ 
        libglvnd-dev libglvnd-dev:i386 \
        libgl1-mesa-dev libgl1-mesa-dev:i386 \
        libegl1-mesa-dev libegl1-mesa-dev:i386 \
        libgles2-mesa-dev libgles2-mesa-dev:i386  \
        mesa-utils    

RUN pip3 install open3d moviepy torch-ema ninja opencv-contrib-python tensorboardX tqdm rich dearpygui  packaging scipy  lpips imageio scikit-image scikit-learn addict trimesh einops tqdm dotmap imageio-ffmpeg  plyfile PyMCubes  pythreejs pandas

RUN conda install -c conda-forge tensorboard
RUN pip3 install moviepy torchviz
RUN pip3 install setuptools==59.5.0 flask==2.1.3
WORKDIR /






